-- drop all tables
DROP TABLE IF EXISTS users_sessions CASCADE;
DROP TABLE IF EXISTS sessions_clans CASCADE;
DROP TABLE IF EXISTS goals CASCADE;
DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS clans CASCADE;
DROP TABLE IF EXISTS news CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS timetables CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;


--localhost addition
ALTER TABLE users
    ADD COLUMN isAdmin BOOLEAN DEFAULT FALSE;