version: "3.8"
services:
  api:
    build:
      context: ./drujite-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: drujite-container
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - images_sessions:/app/storage/images/sessions
      - images_characters:/app/storage/images/characters
      - images_news:/app/storage/images/news
      - images_clothing:/app/storage/images/clothing
      - images_clothingItems:/app/storage/images/clothingItems

  pg:
    image: postgres:latest
    container_name: drujite-pg-container
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "25432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d drujite_pg" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  pg_data:
  images_sessions:
  images_characters:
  images_news:
  images_clothing:
  images_clothingItems: